#!/system/bin/sh

echo 16 > /sys/android_touch/sweep2wake
echo 14789 > /sys/android_touch/s2w_pattern
echo 0 > /sys/android_touch/s2w_symmetric
echo 0 > /sys/android_touch/s2w_vib_on_touch
echo 1 > /sys/android_touch/pocket_detect
echo 40 > /sys/android_touch/vib_strength
